version: '2'

services:
  frameserver:
    build:
      context: .
      args:
        cores: 16
    ports: ['7500:7500']
    volumes: ['./src:/app']
    environment:
      - 'PORT=7500'
      - 'BUCKET=esper'
      - 'WORKERS=16'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
