version: '2'

services:
  frameserver:
    image: scannerresearch/frameserver
    build:
      context: .
      args:
        cores: 16
    ports: ['7501:7500']
    volumes: ['./src:/app', '/:/host', '.:/frameserver']
    environment:
      - 'WORKERS=4'
      - 'AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}'
      - 'AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}'
      - 'FILESYSTEM=local'
      - 'BUCKET=esper'
